<?php

return [
    ['question_key' => 'results_key_achievements', 'section_key' => 'results', 'section_label' => 'Результаты работы', 'label' => 'Назовите 3 ваши ключевые достижения за последние полгода. Почему именно они?', 'question_type' => 'textarea', 'answer_scope' => 'self', 'is_required' => 1, 'sort_order' => 1010],
    ['question_key' => 'results_recurring_difficulties', 'section_key' => 'results', 'section_label' => 'Результаты работы', 'label' => 'С какими повторяющимися трудностями вы сталкивались при выполнении задач? Как вы их решали?', 'question_type' => 'textarea', 'answer_scope' => 'self', 'is_required' => 1, 'sort_order' => 1020],
    ['question_key' => 'results_work_preferences', 'section_key' => 'results', 'section_label' => 'Результаты работы', 'label' => 'Что в вашей работе вам нравится больше всего? Что вызывает напряжение или раздражение?', 'question_type' => 'textarea', 'answer_scope' => 'self', 'is_required' => 1, 'sort_order' => 1030],
    ['question_key' => 'results_department_contribution', 'section_key' => 'results', 'section_label' => 'Результаты работы', 'label' => 'Как вы оцениваете свой вклад в общий результат отдела? Приведите конкретный пример.', 'question_type' => 'textarea', 'answer_scope' => 'self', 'is_required' => 1, 'sort_order' => 1040],
    ['question_key' => 'results_work_organization', 'section_key' => 'results', 'section_label' => 'Результаты работы', 'label' => 'Как вы организуете свою работу, чтобы соблюдать сроки и не перегружаться?', 'question_type' => 'textarea', 'answer_scope' => 'self', 'is_required' => 1, 'sort_order' => 1050],

    ['question_key' => 'collaboration_helped_colleague', 'section_key' => 'collaboration', 'section_label' => 'Взаимодействие с коллегами', 'label' => 'Был ли случай за последние полгода, когда вы помогли коллеге решить сложную задачу?', 'question_type' => 'textarea', 'answer_scope' => 'self', 'is_required' => 1, 'sort_order' => 2010],
    ['question_key' => 'collaboration_adjacent_departments', 'section_key' => 'collaboration', 'section_label' => 'Взаимодействие с коллегами', 'label' => 'С какими смежными отделами взаимодействовать легче всего, а с какими сложнее? Что можно улучшить?', 'question_type' => 'textarea', 'answer_scope' => 'self', 'is_required' => 1, 'sort_order' => 2020],
    ['question_key' => 'collaboration_feedback', 'section_key' => 'collaboration', 'section_label' => 'Взаимодействие с коллегами', 'label' => 'Какую обратную связь вы получаете от руководителя и коллег? Как её используете?', 'question_type' => 'textarea', 'answer_scope' => 'self', 'is_required' => 1, 'sort_order' => 2030],
    ['question_key' => 'collaboration_information_loss', 'section_key' => 'collaboration', 'section_label' => 'Взаимодействие с коллегами', 'label' => 'Были ли ситуации, когда информация от вас или к вам потерялась или пришла не вовремя?', 'question_type' => 'textarea', 'answer_scope' => 'self', 'is_required' => 1, 'sort_order' => 2040],

    ['question_key' => 'development_new_skills', 'section_key' => 'development', 'section_label' => 'Профессиональное развитие и самоопределение', 'label' => 'Что нового вы освоили за последние полгода и как применили в работе?', 'question_type' => 'textarea', 'answer_scope' => 'self', 'is_required' => 1, 'sort_order' => 3010],
    ['question_key' => 'development_strengths', 'section_key' => 'development', 'section_label' => 'Профессиональное развитие и самоопределение', 'label' => 'Какие профессиональные навыки вы считаете своими сильными сторонами? Приведите пример.', 'question_type' => 'textarea', 'answer_scope' => 'self', 'is_required' => 1, 'sort_order' => 3020],
    ['question_key' => 'development_growth_areas', 'section_key' => 'development', 'section_label' => 'Профессиональное развитие и самоопределение', 'label' => 'Какие области требуют дополнительного развития? Что хотите освоить в первую очередь?', 'question_type' => 'textarea', 'answer_scope' => 'self', 'is_required' => 1, 'sort_order' => 3030],
    ['question_key' => 'development_next_year_goals', 'section_key' => 'development', 'section_label' => 'Профессиональное развитие и самоопределение', 'label' => 'Какие цели вы ставите перед собой на следующий год?', 'question_type' => 'textarea', 'answer_scope' => 'self', 'is_required' => 1, 'sort_order' => 3040],

    ['question_key' => 'leadership_initiative', 'section_key' => 'leadership', 'section_label' => 'Лидерский потенциал и инициативность', 'label' => 'Приведите пример, когда вы проявили инициативу в решении рабочей задачи.', 'question_type' => 'textarea', 'answer_scope' => 'self', 'is_required' => 1, 'sort_order' => 4010],
    ['question_key' => 'leadership_criticism', 'section_key' => 'leadership', 'section_label' => 'Лидерский потенциал и инициативность', 'label' => 'Как вы реагируете на замечания и критику? Приведите пример.', 'question_type' => 'textarea', 'answer_scope' => 'self', 'is_required' => 1, 'sort_order' => 4020],
    ['question_key' => 'leadership_priorities', 'section_key' => 'leadership', 'section_label' => 'Лидерский потенциал и инициативность', 'label' => 'Если у вас несколько задач с разными сроками, как расставляете приоритеты?', 'question_type' => 'textarea', 'answer_scope' => 'self', 'is_required' => 1, 'sort_order' => 4030],
    ['question_key' => 'leadership_future_interests', 'section_key' => 'leadership', 'section_label' => 'Лидерский потенциал и инициативность', 'label' => 'Какие задачи или направления в работе отдела вам интересны в перспективе?', 'question_type' => 'textarea', 'answer_scope' => 'self', 'is_required' => 1, 'sort_order' => 4040],
];
