CREATE TABLE IF NOT EXISTS project_cost_plan (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT UNSIGNED NOT NULL,
    num INT NULL,
    section_code VARCHAR(100) NULL,
    sbc_collection VARCHAR(255) NULL,
    sbc_table VARCHAR(120) NULL,
    work_name TEXT NOT NULL,
    unit VARCHAR(120) NULL,
    quantity DECIMAL(12,3) NOT NULL DEFAULT 1,
    base_price DECIMAL(14,2) NOT NULL DEFAULT 0,
    stage_percent DECIMAL(6,2) NOT NULL DEFAULT 100,
    complexity_coeff DECIMAL(10,4) NOT NULL DEFAULT 1,
    deflator_coeff DECIMAL(10,4) NOT NULL DEFAULT 1,
    adjustment_coeff DECIMAL(10,4) NOT NULL DEFAULT 1,
    planned_cost DECIMAL(14,2) NOT NULL DEFAULT 0,
    price_level VARCHAR(80) NULL,
    comments TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_cost_plan_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    INDEX idx_cost_plan_project_num (project_id, num),
    INDEX idx_cost_plan_section (project_id, section_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
