CREATE TABLE IF NOT EXISTS cost_estimates (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT UNSIGNED NULL,
    code VARCHAR(80) NOT NULL,
    title VARCHAR(255) NOT NULL,
    object VARCHAR(255) NULL,
    stage VARCHAR(80) NULL,
    customer VARCHAR(255) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'preproject',
    price_level VARCHAR(80) NULL,
    notes TEXT NULL,
    created_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_cost_estimates_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL,
    CONSTRAINT fk_cost_estimates_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_cost_estimates_status (status),
    INDEX idx_cost_estimates_project (project_id),
    INDEX idx_cost_estimates_updated (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cost_estimate_items (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    estimate_id BIGINT UNSIGNED NOT NULL,
    num INT NULL,
    section_code VARCHAR(100) NULL,
    sbc_item_id BIGINT UNSIGNED NULL,
    sbc_collection VARCHAR(255) NULL,
    sbc_table VARCHAR(120) NULL,
    work_name TEXT NOT NULL,
    unit VARCHAR(120) NULL,
    labor_hours DECIMAL(10,2) NOT NULL DEFAULT 0,
    quantity DECIMAL(12,3) NOT NULL DEFAULT 1,
    base_price DECIMAL(14,2) NOT NULL DEFAULT 0,
    stage_percent DECIMAL(6,2) NOT NULL DEFAULT 100,
    complexity_coeff DECIMAL(10,4) NOT NULL DEFAULT 1,
    deflator_coeff DECIMAL(10,4) NOT NULL DEFAULT 1,
    adjustment_coeff DECIMAL(10,4) NOT NULL DEFAULT 1,
    planned_cost DECIMAL(14,2) NOT NULL DEFAULT 0,
    price_level VARCHAR(80) NULL,
    justification TEXT NULL,
    comments TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_cost_estimate_items_estimate FOREIGN KEY (estimate_id) REFERENCES cost_estimates(id) ON DELETE CASCADE,
    CONSTRAINT fk_cost_estimate_items_sbc FOREIGN KEY (sbc_item_id) REFERENCES sbc_items(id) ON DELETE SET NULL,
    INDEX idx_cost_estimate_items_num (estimate_id, num),
    INDEX idx_cost_estimate_items_section (estimate_id, section_code),
    INDEX idx_cost_estimate_items_sbc (sbc_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
