<?php

declare(strict_types=1);

use App\Controllers\AdminController;
use App\Controllers\AtlasController;
use App\Controllers\CalculatorController;
use App\Controllers\PayrollAdminController;
use App\Controllers\ActivityController;
use App\Controllers\AuthController;
use App\Controllers\CostEstimateController;
use App\Controllers\DprController;
use App\Controllers\DirectorController;
use App\Controllers\CompetencyController;
use App\Controllers\HrController;
use App\Controllers\KnowledgeController;
use App\Controllers\ManualController;
use App\Controllers\MotivationController;
use App\Controllers\OrgController;
use App\Controllers\NotesController;
use App\Controllers\NotificationController;
use App\Controllers\ProjectController;
use App\Controllers\ProjectHealthReportController;
use App\Controllers\ProjectStructureController;
use App\Controllers\ProjectTabController;
use App\Controllers\PushController;
use App\Controllers\PublicLinkController;
use App\Controllers\ReportController;
use App\Controllers\RevitIntegrationController;
use App\Controllers\ResourceController;
use App\Controllers\SearchController;
use App\Controllers\TaskController;
use App\Controllers\TeamController;
use App\Controllers\TimeController;
use App\Controllers\WeeklyReportController;
use App\Controllers\WorkdayController;
use App\Core\Router;

require_once dirname(__DIR__) . '/app/bootstrap.php';

$router = new Router();

$router->get('/', [AuthController::class, 'home']);
$router->get('/login', [AuthController::class, 'loginForm']);
$router->post('/login', [AuthController::class, 'login']);
$router->post('/demo-login', [AuthController::class, 'demoLogin']);
$router->post('/logout', [AuthController::class, 'logout']);
$router->get('/password/change', [AuthController::class, 'passwordForm']);
$router->post('/password/change', [AuthController::class, 'passwordChange']);
$router->get('/p/{token}', [PublicLinkController::class, 'project']);
$router->get('/t/{token}', [PublicLinkController::class, 'task']);
$router->get('/m/{token}', [PublicLinkController::class, 'model']);

$router->get('/api/revit/v1/capabilities', [RevitIntegrationController::class, 'capabilities']);
$router->post('/api/revit/v1/activation/exchange', [RevitIntegrationController::class, 'exchange']);
$router->get('/api/revit/v1/projects', [RevitIntegrationController::class, 'projects']);
$router->get('/api/revit/v1/projects/{projectId}/models', [RevitIntegrationController::class, 'models']);
$router->post('/api/revit/v1/projects/{projectId}/models', [RevitIntegrationController::class, 'createModel']);
$router->post('/api/revit/v1/models/{modelId}/uploads', [RevitIntegrationController::class, 'startUpload']);
$router->get('/api/revit/v1/uploads/{uploadId}', [RevitIntegrationController::class, 'uploadStatus']);
$router->post('/api/revit/v1/uploads/{uploadId}/chunks/{index}', [RevitIntegrationController::class, 'uploadChunk']);
$router->post('/api/revit/v1/uploads/{uploadId}/complete', [RevitIntegrationController::class, 'completeUpload']);

$router->get('/locia', [TaskController::class, 'locia']);
$router->get('/work', [TaskController::class, 'locia']);
$router->get('/atlas', [AtlasController::class, 'viewer']);
$router->get('/calculator', [CalculatorController::class, 'index']);
$router->get('/calculator/api/rates', [CalculatorController::class, 'rates']);
$router->post('/calculator/api/portfolio', [CalculatorController::class, 'savePortfolio']);
$router->post('/calculator/api/portfolio/{snapshotId}/delete', [CalculatorController::class, 'deletePortfolio']);
$router->get('/calculator/assets/{file}', [CalculatorController::class, 'asset']);
$router->get('/knowledge', [KnowledgeController::class, 'index']);
$router->get('/knowledge/folders/new', [KnowledgeController::class, 'newFolder']);
$router->post('/knowledge/folders/new', [KnowledgeController::class, 'storeFolder']);
$router->get('/knowledge/folders/{id}', [KnowledgeController::class, 'index']);
$router->get('/knowledge/folders/{id}/edit', [KnowledgeController::class, 'editFolder']);
$router->post('/knowledge/folders/{id}', [KnowledgeController::class, 'updateFolder']);
$router->get('/knowledge/documents/new', [KnowledgeController::class, 'newDocument']);
$router->post('/knowledge/documents/new', [KnowledgeController::class, 'storeDocument']);
$router->get('/knowledge/documents/{id}', [KnowledgeController::class, 'showDocument']);
$router->get('/knowledge/documents/{id}/edit', [KnowledgeController::class, 'editDocument']);
$router->post('/knowledge/documents/{id}/draft', [KnowledgeController::class, 'saveDraft']);
$router->post('/knowledge/documents/{id}/autosave', [KnowledgeController::class, 'autosave']);
$router->post('/knowledge/documents/{id}/publish', [KnowledgeController::class, 'publish']);
$router->post('/knowledge/documents/{id}/archive', [KnowledgeController::class, 'archive']);
$router->post('/knowledge/documents/{id}/revisions/{revisionId}/restore', [KnowledgeController::class, 'restoreRevision']);
$router->get('/locia-atlas/api/default-model', [AtlasController::class, 'defaultModel']);
$router->get('/locia-atlas/default-folder/file', [AtlasController::class, 'defaultModelFile']);
$router->get('/locia-atlas/default-folder/fragments/status', [AtlasController::class, 'defaultModelFragmentsStatus']);
$router->get('/locia-atlas/default-folder/fragments', [AtlasController::class, 'defaultModelFragmentsGet']);
$router->post('/locia-atlas/default-folder/fragments', [AtlasController::class, 'defaultModelFragmentsPost']);
$router->get('/manual', [ManualController::class, 'index']);
$router->get('/manual/regulation', [ManualController::class, 'regulation']);
$router->get('/notifications', [NotificationController::class, 'index']);
$router->post('/notifications/read', [NotificationController::class, 'markRead']);
$router->get('/push/config', [PushController::class, 'config']);
$router->post('/push/subscribe', [PushController::class, 'subscribe']);
$router->post('/push/unsubscribe', [PushController::class, 'unsubscribe']);
$router->post('/push/test', [PushController::class, 'test']);
$router->get('/activity', [ActivityController::class, 'index']);
$router->get('/search', [SearchController::class, 'index']);
$router->get('/my-day', [WorkdayController::class, 'index']);
$router->get('/notes', [NotesController::class, 'index']);
$router->get('/notes/new', [NotesController::class, 'create']);
$router->post('/notes/new', [NotesController::class, 'store']);
$router->get('/notes/{id}', [NotesController::class, 'show']);
$router->post('/notes/{id}', [NotesController::class, 'update']);
$router->post('/notes/{id}/status', [NotesController::class, 'status']);
$router->post('/notes/{id}/convert', [NotesController::class, 'convert']);
$router->get('/tasks', [TaskController::class, 'mine']);
$router->get('/tasks/all', [TaskController::class, 'all']);
$router->get('/tasks/table', [TaskController::class, 'table']);
$router->get('/tasks/board', [TaskController::class, 'board']);
$router->get('/tasks/bim-family', [TaskController::class, 'bimFamilyRegistry']);
$router->get('/time', [TimeController::class, 'index']);
$router->post('/time/week', [TimeController::class, 'saveWeek']);
$router->post('/time/distribute', [TimeController::class, 'distributeDay']);
$router->post('/time/task', [TimeController::class, 'taskEntry']);
$router->get('/time/approvals', [TimeController::class, 'approvals']);
$router->post('/time/approvals/{id}/gip-approve', [TimeController::class, 'gipApproveMonth']);
$router->post('/time/approvals/{id}/department-approve', [TimeController::class, 'departmentApproveMonth']);
$router->post('/time/approvals/{id}/director-approve', [TimeController::class, 'directorApproveMonth']);
$router->post('/time/approvals/{id}/return', [TimeController::class, 'returnMonth']);
$router->post('/time/approvals/{id}/reopen', [TimeController::class, 'reopenMonth']);
$router->get('/tasks/new', [TaskController::class, 'createForm']);
$router->post('/tasks/new', [TaskController::class, 'store']);
$router->get('/tasks/{id}', [TaskController::class, 'show']);
$router->post('/tasks/{id}', [TaskController::class, 'update']);
$router->post('/tasks/{id}/status', [TaskController::class, 'status']);
$router->post('/tasks/{id}/assignment-response', [TaskController::class, 'assignmentResponse']);
$router->post('/tasks/{id}/delegation/take', [TaskController::class, 'takeDelegation']);
$router->post('/tasks/{id}/delegation/return', [TaskController::class, 'returnDelegation']);
$router->post('/tasks/{id}/comments', [TaskController::class, 'comment']);
$router->post('/tasks/{id}/attachments', [TaskController::class, 'uploadAttachments']);
$router->get('/tasks/{id}/attachments/{attachmentId}', [TaskController::class, 'downloadAttachment']);
$router->post('/tasks/{id}/attachments/{attachmentId}/delete', [TaskController::class, 'deleteAttachment']);
$router->post('/tasks/{id}/issues', [TaskController::class, 'storeIssue']);
$router->post('/tasks/{id}/issues/{issueId}/close', [TaskController::class, 'closeIssue']);
$router->post('/tasks/{id}/approval/submit', [TaskController::class, 'submitApproval']);
$router->post('/tasks/{id}/approval/lead', [TaskController::class, 'leadApproval']);
$router->post('/tasks/{id}/approval/gip', [TaskController::class, 'gipApproval']);
$router->post('/tasks/{id}/labor-estimate/submit', [TaskController::class, 'submitLaborEstimate']);
$router->post('/tasks/{id}/labor-estimate/gip', [TaskController::class, 'gipLaborEstimate']);
$router->post('/tasks/{id}/labor-estimate/gip-return', [TaskController::class, 'returnLaborEstimateToResponsible']);
$router->post('/tasks/{id}/labor-estimate/director', [TaskController::class, 'directorLaborEstimate']);
$router->post('/tasks/{id}/labor-estimate/director-return', [TaskController::class, 'returnLaborEstimateToGip']);
$router->post('/tasks/{id}/issuances', [TaskController::class, 'storeIssuance']);
$router->post('/tasks/{id}/close-request', [TaskController::class, 'requestClose']);
$router->post('/tasks/{id}/review-cycle', [TaskController::class, 'reviewCycleDecision']);
$router->post('/tasks/{id}/accept-close', [TaskController::class, 'acceptClose']);
$router->post('/tasks/{id}/admin-close', [TaskController::class, 'adminClose']);
$router->post('/tasks/{id}/delete', [TaskController::class, 'delete']);
$router->post('/tasks/{id}/shift-deadline', [TaskController::class, 'shiftDeadline']);
$router->post('/tasks/{id}/deadline-shifts/{shiftId}/approve', [TaskController::class, 'approveDeadlineShift']);
$router->post('/tasks/{id}/deadline-shifts/{shiftId}/reject', [TaskController::class, 'rejectDeadlineShift']);

$router->get('/projects', [ProjectController::class, 'index']);
$router->get('/projects/archived', [ProjectController::class, 'archived']);
$router->get('/projects/new', [ProjectController::class, 'create']);
$router->post('/projects/new', [ProjectController::class, 'store']);
$router->get('/projects/{id}', [ProjectController::class, 'show']);
$router->get('/projects/{id}/structure', [ProjectStructureController::class, 'show']);
$router->post('/projects/{id}/structure/stages', [ProjectStructureController::class, 'addStage']);
$router->post('/projects/{id}/structure/items', [ProjectStructureController::class, 'addItem']);
$router->post('/projects/{id}/structure/assignments', [ProjectStructureController::class, 'assignmentsTable']);
$router->post('/projects/{id}/structure/items/{sectionId}/assignments', [ProjectStructureController::class, 'assignments']);
$router->get('/projects/{id}/health-report', [ProjectHealthReportController::class, 'show']);
$router->post('/projects/{id}/health-report/comment', [ProjectHealthReportController::class, 'comment']);
$router->post('/projects/{id}', [ProjectController::class, 'update']);
$router->post('/projects/{id}/msp-import', [ProjectController::class, 'mspImport']);
$router->post('/projects/{id}/archive', [ProjectController::class, 'archive']);
$router->post('/projects/{id}/restore', [ProjectController::class, 'restore']);
$router->post('/projects/{id}/clone', [ProjectController::class, 'clone']);
$router->post('/projects/{id}/contacts', [ProjectController::class, 'storeContact']);
$router->post('/projects/{id}/contacts/{contactId}/delete', [ProjectController::class, 'deleteContact']);
$router->post('/projects/{id}/budget', [ProjectController::class, 'storeBudget']);
$router->post('/projects/{id}/members', [ProjectController::class, 'storeMember']);
$router->post('/projects/{id}/team-structure', [ProjectController::class, 'storeTeamStructure']);
$router->post('/projects/{id}/team-section', [ProjectController::class, 'assignTeamSection']);
$router->post('/projects/{id}/members/{memberId}/delete', [ProjectController::class, 'deleteMember']);
$router->post('/projects/{id}/models', [ProjectController::class, 'storeModelLink']);
$router->post('/projects/{id}/model-folder', [ProjectController::class, 'storeModelFolder']);
$router->post('/projects/{id}/model-folder/refresh', [ProjectController::class, 'refreshModelFolder']);
$router->post('/projects/{id}/models/{modelId}/delete', [ProjectController::class, 'deleteModelLink']);
$router->get('/projects/{id}/models/{modelId}/file', [ProjectController::class, 'modelFile']);
$router->get('/projects/{id}/model-folder/file', [ProjectController::class, 'folderModelFile']);
$router->get('/projects/{id}/model-folder/fragments/status', [ProjectController::class, 'folderModelFragmentsStatus']);
$router->get('/projects/{id}/model-folder/fragments', [ProjectController::class, 'folderModelFragmentsGet']);
$router->post('/projects/{id}/model-folder/fragments', [ProjectController::class, 'folderModelFragmentsPost']);
$router->get('/projects/{id}/models/{modelId}/fragments', [ProjectController::class, 'modelFragmentsGet']);
$router->post('/projects/{id}/models/{modelId}/fragments', [ProjectController::class, 'modelFragmentsPost']);
$router->post('/projects/{id}/folders/open', [ProjectController::class, 'openFolder']);
$router->get('/projects/{id}/assistant', [ProjectController::class, 'assistant']);
$router->get('/projects/{id}/tasks', [ProjectController::class, 'tasksPage']);
$router->post('/projects/{id}/task-templates/{type}', [ProjectController::class, 'seedTaskTemplate']);
$router->get('/projects/{id}/gantt', [ProjectController::class, 'gantt']);
$router->get('/projects/{id}/dictionaries', [ProjectController::class, 'dictionaries']);
$router->post('/projects/{id}/dictionaries', [ProjectController::class, 'storeDictionary']);
$router->post('/projects/{id}/accounting/pp', [ProjectController::class, 'storeAccountingPp']);
$router->post('/projects/{id}/accounting/btp', [ProjectController::class, 'storeAccountingBtp']);
$router->post('/projects/{id}/accounting/uts', [ProjectController::class, 'storeAccountingUts']);
$router->get('/projects/{id}/schedule', [ProjectTabController::class, 'schedule']);
$router->get('/projects/{id}/sections', [ProjectTabController::class, 'sections']);
$router->get('/projects/{id}/issues', [ProjectTabController::class, 'issues']);
$router->get('/projects/{id}/data', [ProjectTabController::class, 'data']);
$router->get('/projects/{id}/exchange', [ProjectTabController::class, 'exchange']);
$router->get('/projects/{id}/costs', [ProjectTabController::class, 'costs']);
$router->post('/projects/{id}/schedule/sync', [ProjectTabController::class, 'syncSchedule']);
$router->post('/projects/{id}/sections/template/{type}', [ProjectTabController::class, 'seedSectionsTemplate']);
$router->post('/projects/{id}/sections/sync', [ProjectTabController::class, 'syncSections']);
$router->post('/projects/{id}/issues/sync', [ProjectTabController::class, 'syncIssues']);
$router->post('/projects/{id}/data/template', [ProjectTabController::class, 'seedDataTemplate']);
$router->post('/projects/{id}/exchange/sync', [ProjectTabController::class, 'syncExchange']);
$router->post('/projects/{id}/exchange/templates/apply', [ProjectTabController::class, 'applyExchangeTemplate']);
$router->post('/projects/{id}/costs/sync', [ProjectTabController::class, 'syncCosts']);
$router->post('/projects/{id}/costs/{rowId}/labor-approval', [ProjectTabController::class, 'costLaborApproval']);
$router->post('/projects/{id}/tabs/{kind}', [ProjectTabController::class, 'store']);
$router->post('/projects/{id}/tabs/{kind}/import', [ProjectTabController::class, 'importCsv']);

$router->get('/cost-estimates', [CostEstimateController::class, 'index']);
$router->post('/cost-estimates', [CostEstimateController::class, 'store']);
$router->get('/cost-estimates/rates', [CostEstimateController::class, 'rates']);
$router->post('/cost-estimates/rates', [CostEstimateController::class, 'updateRate']);
$router->get('/cost-estimates/{id}', [CostEstimateController::class, 'show']);
$router->post('/cost-estimates/{id}', [CostEstimateController::class, 'update']);
$router->post('/cost-estimates/{id}/sections', [CostEstimateController::class, 'storeSection']);
$router->post('/cost-estimates/{id}/sections/bulk-sbc', [CostEstimateController::class, 'bulkSectionSbc']);
$router->post('/cost-estimates/{id}/sections/bulk-labor', [CostEstimateController::class, 'bulkLaborEstimates']);
$router->post('/cost-estimates/{id}/sections/{sectionId}', [CostEstimateController::class, 'updateSection']);
$router->post('/cost-estimates/{id}/sections/{sectionId}/delete', [CostEstimateController::class, 'deleteSection']);
$router->post('/cost-estimates/{id}/labor-estimates', [CostEstimateController::class, 'storeLaborEstimate']);
$router->post('/cost-estimates/{id}/labor-estimates/{estimateId}/department-submit', [CostEstimateController::class, 'submitDepartmentEstimate']);
$router->post('/cost-estimates/{id}/labor-estimates/{estimateId}/gip', [CostEstimateController::class, 'gipAdjustEstimate']);
$router->post('/cost-estimates/{id}/labor-estimates/{estimateId}/gip-return', [CostEstimateController::class, 'gipReturnEstimate']);
$router->post('/cost-estimates/{id}/labor-estimates/{estimateId}/director', [CostEstimateController::class, 'directorApproveEstimate']);
$router->post('/cost-estimates/{id}/sbc-indices', [CostEstimateController::class, 'saveSbcIndex']);
$router->post('/cost-estimates/{id}/sbc-seed', [CostEstimateController::class, 'seedBundledSbc']);
$router->post('/cost-estimates/{id}/convert', [CostEstimateController::class, 'convertToProject']);

$router->get('/motivation', [MotivationController::class, 'index']);
$router->post('/motivation/lock', [MotivationController::class, 'lock']);
$router->get('/motivation/projects', [MotivationController::class, 'projects']);
$router->post('/motivation/projects', [MotivationController::class, 'saveProject']);
$router->get('/motivation/settings', [MotivationController::class, 'settings']);
$router->post('/motivation/settings', [MotivationController::class, 'saveSettings']);

$router->get('/hr', [HrController::class, 'index']);
$router->get('/hr/cycles/new', [HrController::class, 'newCycle']);
$router->get('/hr/cycles/{id}', [HrController::class, 'showCycle']);
$router->get('/hr/reviews', [HrController::class, 'hrReviews']);
$router->get('/hr/reviews/{id}', [HrController::class, 'showReview']);
$router->get('/performance-review', [HrController::class, 'reviews']);
$router->get('/performance-review/manager', [HrController::class, 'managerReviews']);
$router->get('/performance-review/{id}', [HrController::class, 'showReview']);
$router->get('/performance-review/{id}/export', [HrController::class, 'exportReview']);
$router->post('/performance-review/{id}/questionnaire/draft', [HrController::class, 'saveSelfDraft']);
$router->post('/performance-review/{id}/questionnaire/submit', [HrController::class, 'submitSelf']);
$router->post('/performance-review/{id}/competencies/{scope}/draft', [HrController::class, 'saveCompetencyDraft']);
$router->post('/performance-review/{id}/competencies/{scope}/submit', [HrController::class, 'submitCompetency']);
$router->post('/performance-review/{id}/meeting/complete', [HrController::class, 'completeMeeting']);
$router->post('/hr/reviews/{id}/manager-assign', [HrController::class, 'assignManager']);
$router->get('/hr/templates', [HrController::class, 'templates']);
$router->post('/hr/templates', [HrController::class, 'createTemplate']);
$router->post('/hr/templates/questions', [HrController::class, 'addQuestion']);
$router->post('/hr/templates/questions/{id}', [HrController::class, 'updateQuestion']);
$router->post('/hr/cycles', [HrController::class, 'createCycle']);
$router->get('/hr/cycles/{id}/edit', [HrController::class, 'editCycle']);
$router->get('/hr/cycles/{id}/summary', [HrController::class, 'cycleSummary']);
$router->get('/hr/cycles/{id}/export', [HrController::class, 'exportCycle']);
$router->post('/hr/cycles/{id}', [HrController::class, 'updateCycle']);
$router->post('/hr/cycles/{id}/open', [HrController::class, 'openCycle']);
$router->post('/hr/cycles/{id}/close', [HrController::class, 'closeCycle']);
$router->post('/hr/cycles/{id}/reopen', [HrController::class, 'reopenCycle']);
$router->post('/hr/cycles/{id}/make-official', [HrController::class, 'makeCycleOfficial']);

$router->get('/gantt', [ProjectController::class, 'ganttHome']);

$router->get('/shturman', [DprController::class, 'index']);
$router->get('/golem', [DprController::class, 'legacy']);
$router->get('/dpr', [DprController::class, 'legacy']);

$router->get('/profile', [ReportController::class, 'profile']);
$router->get('/profiles', [ReportController::class, 'profile']);
$router->get('/profiles/{id}', [ReportController::class, 'profile']);
$router->post('/profile/revit/code', [RevitIntegrationController::class, 'issueCode']);
$router->post('/profile/revit/tokens/{tokenId}/revoke', [RevitIntegrationController::class, 'revokeToken']);
$router->post('/my-day/vacations', [WorkdayController::class, 'createVacation']);
$router->post('/my-day/vacations/{id}/cancel', [WorkdayController::class, 'cancelVacation']);
$router->get('/revit/versions/{versionId}/file', [RevitIntegrationController::class, 'versionFile']);
$router->post('/projects/{projectId}/revit-models/{seriesId}/versions/{versionId}/current', [RevitIntegrationController::class, 'setCurrent']);
$router->post('/projects/{projectId}/revit-models/{seriesId}/versions/{versionId}/delete', [RevitIntegrationController::class, 'deleteVersion']);
$router->get('/team', [TeamController::class, 'employees']);
$router->get('/team/employees', [TeamController::class, 'employees']);
$router->get('/team/employees/new', [TeamController::class, 'newEmployee']);
$router->get('/team/employees/{id}/edit', [TeamController::class, 'editEmployee']);
$router->post('/team/employees/{id}', [TeamController::class, 'updateEmployee']);
$router->post('/team/employees/{id}/quick-update', [TeamController::class, 'quickUpdateEmployee']);
$router->get('/team/structure', [OrgController::class, 'index']);
$router->get('/team/departments', [TeamController::class, 'departments']);
$router->post('/team/departments', [AdminController::class, 'storeDepartment']);
$router->post('/team/departments/{id}', [AdminController::class, 'updateDepartment']);
$router->post('/team/departments/{id}/delete', [AdminController::class, 'deleteDepartment']);
$router->post('/team/department-groups', [AdminController::class, 'storeDepartmentGroup']);
$router->post('/team/department-groups/{id}', [AdminController::class, 'updateDepartmentGroup']);
$router->post('/team/department-groups/{id}/delete', [AdminController::class, 'deleteDepartmentGroup']);
$router->get('/team/positions', [TeamController::class, 'positions']);
$router->post('/team/positions', [TeamController::class, 'createPosition']);
$router->post('/team/positions/{id}', [TeamController::class, 'updatePosition']);
$router->post('/team/positions/{id}/clone', [TeamController::class, 'clonePosition']);
$router->post('/team/positions/{id}/archive', [TeamController::class, 'archivePosition']);
$router->get('/team/rates', [TeamController::class, 'rates']);
$router->get('/team/staffing', [TeamController::class, 'legacyStaffing']);
$router->get('/director/staffing', [TeamController::class, 'staffing']);
$router->get('/director/portfolio', [DirectorController::class, 'portfolio']);
$router->post('/director/staffing/periods', [TeamController::class, 'createStaffingPeriod']);
$router->post('/director/staffing/periods/{id}', [TeamController::class, 'updateStaffingPeriod']);
$router->post('/director/staffing/periods/{id}/lock', [TeamController::class, 'lockStaffingPeriod']);
$router->post('/director/staffing/periods/{id}/correct', [TeamController::class, 'correctStaffingPeriod']);
$router->get('/director/staffing/periods/{id}/print', [TeamController::class, 'printStaffing']);
$router->get('/director/staffing/periods/{id}/export', [TeamController::class, 'exportStaffing']);
$router->post('/director/staffing/periods/{id}/rows', [TeamController::class, 'saveStaffingRow']);
$router->post('/director/staffing/periods/{id}/rows/{rowId}', [TeamController::class, 'saveStaffingRow']);
$router->post('/director/staffing/periods/{id}/rows/{rowId}/delete', [TeamController::class, 'deleteStaffingRow']);
$router->get('/director/budget', [DirectorController::class, 'budget']);
$router->post('/director/budget/projects/{id}', [DirectorController::class, 'saveProjectBudget']);
$router->post('/director/budget/payments', [DirectorController::class, 'savePayment']);
$router->post('/director/budget/payments/{id}', [DirectorController::class, 'savePayment']);
$router->post('/director/budget/payments/{id}/delete', [DirectorController::class, 'deletePayment']);
$router->get('/reports', [ReportController::class, 'index']);
$router->get('/resources', [ResourceController::class, 'index']);
$router->get('/reports/periodic', [WeeklyReportController::class, 'index']);
$router->post('/reports/periodic', [WeeklyReportController::class, 'create']);
$router->get('/reports/periodic/{id}', [WeeklyReportController::class, 'show']);
$router->post('/reports/periodic/{id}', [WeeklyReportController::class, 'update']);
$router->post('/reports/periodic/{id}/items', [WeeklyReportController::class, 'addItem']);
$router->post('/reports/periodic/{id}/items/{itemId}/delete', [WeeklyReportController::class, 'deleteItem']);
$router->post('/reports/periodic/{id}/lock', [WeeklyReportController::class, 'lock']);
$router->get('/reports/weekly', [WeeklyReportController::class, 'index']);
$router->post('/reports/weekly', [WeeklyReportController::class, 'create']);
$router->get('/reports/weekly/{id}', [WeeklyReportController::class, 'show']);
$router->post('/reports/weekly/{id}', [WeeklyReportController::class, 'update']);
$router->post('/reports/weekly/{id}/items', [WeeklyReportController::class, 'addItem']);
$router->post('/reports/weekly/{id}/items/{itemId}/delete', [WeeklyReportController::class, 'deleteItem']);
$router->post('/reports/weekly/{id}/lock', [WeeklyReportController::class, 'lock']);
$router->get('/reports/people', [ReportController::class, 'people']);
$router->post('/reports/people/time-approve', [ReportController::class, 'approvePeopleTime']);
$router->post('/reports', [ReportController::class, 'index']);
$router->post('/reports/export', [ReportController::class, 'export']);

$router->get('/admin/users', [AdminController::class, 'users']);
$router->post('/admin/users', [AdminController::class, 'storeUser']);
$router->get('/admin/users/import', [AdminController::class, 'importUsersForm']);
$router->post('/admin/users/import', [AdminController::class, 'importUsers']);
$router->post('/admin/users/reset-passwords', [AdminController::class, 'resetPasswords']);
$router->post('/admin/users/{id}/identity', [AdminController::class, 'updateUserIdentity']);
$router->post('/admin/users/{id}/role', [AdminController::class, 'updateRole']);
$router->post('/admin/users/{id}/department', [AdminController::class, 'updateUserDepartment']);
$router->post('/admin/users/{id}/org', [AdminController::class, 'updateUserOrg']);
$router->post('/admin/users/{id}/org-placement', [AdminController::class, 'updateUserOrgPlacement']);
$router->post('/admin/users/{id}/rate', [AdminController::class, 'updateUserRate']);
$router->post('/admin/users/{id}/active', [AdminController::class, 'updateUserActive']);
$router->post('/admin/users/{id}/reset-password', [AdminController::class, 'resetPassword']);
$router->post('/admin/users/{id}/credentials-mail-sent', [AdminController::class, 'markCredentialsMailSent']);
$router->get('/admin/departments', [AdminController::class, 'departments']);
$router->post('/admin/departments', [AdminController::class, 'storeDepartment']);
$router->post('/admin/departments/{id}', [AdminController::class, 'updateDepartment']);
$router->post('/admin/departments/{id}/delete', [AdminController::class, 'deleteDepartment']);
$router->post('/admin/department-groups', [AdminController::class, 'storeDepartmentGroup']);
$router->post('/admin/department-groups/{id}', [AdminController::class, 'updateDepartmentGroup']);
$router->post('/admin/department-groups/{id}/delete', [AdminController::class, 'deleteDepartmentGroup']);
// ФОТ-модуль (Фаза 1): юрлица, статьи списания, ставки сотрудник×юрлицо
$router->get('/admin/legal-entities', [PayrollAdminController::class, 'legalEntities']);
$router->post('/admin/legal-entities', [PayrollAdminController::class, 'storeLegalEntity']);
$router->post('/admin/legal-entities/{id}/delete', [PayrollAdminController::class, 'deleteLegalEntity']);
$router->get('/admin/writeoff-articles', [PayrollAdminController::class, 'articles']);
$router->post('/admin/writeoff-articles', [PayrollAdminController::class, 'storeArticle']);
$router->post('/admin/writeoff-articles/{id}/delete', [PayrollAdminController::class, 'deleteArticle']);
$router->get('/admin/employee-entities', [PayrollAdminController::class, 'employeeEntities']);
$router->post('/admin/employee-entities', [PayrollAdminController::class, 'storeEmployeeEntity']);
$router->post('/admin/employee-entities/{id}/delete', [PayrollAdminController::class, 'deleteEmployeeEntity']);
$router->get('/admin/competencies', [CompetencyController::class, 'index']);
$router->get('/admin/org-structure', [OrgController::class, 'index']);
$router->get('/admin/access', [AdminController::class, 'access']);
$router->post('/admin/access', [AdminController::class, 'updateAccess']);
$router->get('/admin/fields', [AdminController::class, 'fields']);
$router->post('/admin/fields', [AdminController::class, 'storeField']);
$router->get('/admin/dictionaries', [AdminController::class, 'dictionaries']);
$router->post('/admin/dictionaries', [AdminController::class, 'storeDictionary']);
$router->get('/admin/counterparties', [AdminController::class, 'counterparties']);
$router->post('/admin/counterparties', [AdminController::class, 'storeCounterparty']);
$router->get('/admin/exchange-templates', [AdminController::class, 'exchangeTemplates']);
$router->post('/admin/exchange-templates', [AdminController::class, 'storeExchangeTemplate']);
$router->post('/admin/exchange-templates/items', [AdminController::class, 'storeExchangeTemplateItem']);
$router->get('/admin/notifications', [AdminController::class, 'notifications']);
$router->post('/admin/notifications/settings', [AdminController::class, 'notificationSettingsSave']);
$router->post('/admin/notifications/send-queue', [AdminController::class, 'notificationQueueSend']);
$router->get('/admin/notifications/{type}/edit', [AdminController::class, 'notificationEdit']);
$router->post('/admin/notifications/{type}/edit', [AdminController::class, 'notificationSave']);
$router->get('/admin/updates', [AdminController::class, 'updates']);
$router->post('/admin/updates/check', [AdminController::class, 'updateCheck']);
$router->post('/admin/updates/download', [AdminController::class, 'updateDownload']);
$router->post('/admin/updates/install', [AdminController::class, 'updateInstall']);
$router->post('/admin/updates/telemetry', [AdminController::class, 'updateTelemetry']);
$router->get('/admin/integrations', [AdminController::class, 'integrations']);
$router->get('/admin/cloud-transfer', [AdminController::class, 'cloudTransfer']);
$router->post('/admin/cloud-transfer/export', [AdminController::class, 'cloudTransferExport']);
$router->post('/admin/cloud-transfer/inspect', [AdminController::class, 'cloudTransferInspect']);
$router->post('/admin/cloud-transfer/apply', [AdminController::class, 'cloudTransferApply']);
$router->post('/admin/integrations/sbc', [AdminController::class, 'sbcImport']);
$router->post('/admin/integrations/sbc/builtin', [AdminController::class, 'sbcSeedBuiltin']);
$router->get('/admin/integrations/sbc/template', [AdminController::class, 'sbcTemplate']);
$router->get('/admin/password-gen', [AdminController::class, 'passwordGenerator']);

$router->dispatch(request_method(), request_path());
